// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtCVE7o1QU8t10aLuIGHEko97jIwIRQ00',
    appId: '1:288421031177:web:4e9df8ef043718930b77d8',
    messagingSenderId: '288421031177',
    projectId: 'taskapp-ee5e1',
    authDomain: 'taskapp-ee5e1.firebaseapp.com',
    storageBucket: 'taskapp-ee5e1.firebasestorage.app',
    measurementId: 'G-241HKZ7N66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6y_8i_mq6Atq1-Az8G4W5Ggi3lNnOMrs',
    appId: '1:288421031177:android:54420b761d4ad6420b77d8',
    messagingSenderId: '288421031177',
    projectId: 'taskapp-ee5e1',
    storageBucket: 'taskapp-ee5e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOb7Zn2Jk-kykqqGfzDEkmmdlj8v7jp4U',
    appId: '1:288421031177:ios:29f1e68782e85b1e0b77d8',
    messagingSenderId: '288421031177',
    projectId: 'taskapp-ee5e1',
    storageBucket: 'taskapp-ee5e1.firebasestorage.app',
    iosBundleId: 'com.example.taskapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOb7Zn2Jk-kykqqGfzDEkmmdlj8v7jp4U',
    appId: '1:288421031177:ios:29f1e68782e85b1e0b77d8',
    messagingSenderId: '288421031177',
    projectId: 'taskapp-ee5e1',
    storageBucket: 'taskapp-ee5e1.firebasestorage.app',
    iosBundleId: 'com.example.taskapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtCVE7o1QU8t10aLuIGHEko97jIwIRQ00',
    appId: '1:288421031177:web:3e458467abfff0370b77d8',
    messagingSenderId: '288421031177',
    projectId: 'taskapp-ee5e1',
    authDomain: 'taskapp-ee5e1.firebaseapp.com',
    storageBucket: 'taskapp-ee5e1.firebasestorage.app',
    measurementId: 'G-S2TZ5DXV1M',
  );

}